/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as StartDemoRouteImport } from './routes/start-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WebsiteServicesRouteImport } from './routes/website/services'
import { Route as WebsiteProductsRouteImport } from './routes/website/products'
import { Route as WebsiteMembershipsRouteImport } from './routes/website/memberships'
import { Route as WebsiteLocationsRouteImport } from './routes/website/locations'
import { Route as WebsiteJoinRouteImport } from './routes/website/join'
import { Route as WebsiteEventsRouteImport } from './routes/website/events'
import { Route as WebsiteConsultationsRouteImport } from './routes/website/consultations'
import { Route as WebsiteBookRouteImport } from './routes/website/book'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as ClientScheduleRouteImport } from './routes/client/schedule'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientBillingRouteImport } from './routes/client/billing'
import { Route as AdminViewMembersRouteImport } from './routes/admin/view-members'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCheckInRouteImport } from './routes/admin/check-in'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as WebsiteServicesServiceIdRouteImport } from './routes/website/services.$serviceId'
import { Route as OwnerOwnerSettingsRouteImport } from './routes/owner/owner.settings'
import { Route as OwnerOwnerRevenueRouteImport } from './routes/owner/owner.revenue'
import { Route as OwnerOwnerRetentionRouteImport } from './routes/owner/owner.retention'
import { Route as OwnerOwnerOverviewRouteImport } from './routes/owner/owner.overview'
import { Route as AdminCreateCreateScheduleRouteImport } from './routes/admin/create/create.schedule'
import { Route as AdminCreateCreateEventRouteImport } from './routes/admin/create/create.event'
import { Route as AdminCreateCreateClientMembershipRouteImport } from './routes/admin/create/create.client-membership'
import { Route as AdminCreateCreateBookingRouteImport } from './routes/admin/create/create.booking'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoRoute = StartDemoRouteImport.update({
  id: '/start-demo',
  path: '/start-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteServicesRoute = WebsiteServicesRouteImport.update({
  id: '/website/services',
  path: '/website/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteProductsRoute = WebsiteProductsRouteImport.update({
  id: '/website/products',
  path: '/website/products',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteMembershipsRoute = WebsiteMembershipsRouteImport.update({
  id: '/website/memberships',
  path: '/website/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLocationsRoute = WebsiteLocationsRouteImport.update({
  id: '/website/locations',
  path: '/website/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteJoinRoute = WebsiteJoinRouteImport.update({
  id: '/website/join',
  path: '/website/join',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteEventsRoute = WebsiteEventsRouteImport.update({
  id: '/website/events',
  path: '/website/events',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteConsultationsRoute = WebsiteConsultationsRouteImport.update({
  id: '/website/consultations',
  path: '/website/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteBookRoute = WebsiteBookRouteImport.update({
  id: '/website/book',
  path: '/website/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientScheduleRoute = ClientScheduleRouteImport.update({
  id: '/client/schedule',
  path: '/client/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBillingRoute = ClientBillingRouteImport.update({
  id: '/client/billing',
  path: '/client/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewMembersRoute = AdminViewMembersRouteImport.update({
  id: '/admin/view-members',
  path: '/admin/view-members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/admin/check-in',
  path: '/admin/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteServicesServiceIdRoute =
  WebsiteServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => WebsiteServicesRoute,
  } as any)
const OwnerOwnerSettingsRoute = OwnerOwnerSettingsRouteImport.update({
  id: '/owner/owner/settings',
  path: '/owner/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOwnerRevenueRoute = OwnerOwnerRevenueRouteImport.update({
  id: '/owner/owner/revenue',
  path: '/owner/owner/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOwnerRetentionRoute = OwnerOwnerRetentionRouteImport.update({
  id: '/owner/owner/retention',
  path: '/owner/owner/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOwnerOverviewRoute = OwnerOwnerOverviewRouteImport.update({
  id: '/owner/owner/overview',
  path: '/owner/owner/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateCreateScheduleRoute =
  AdminCreateCreateScheduleRouteImport.update({
    id: '/admin/create/create/schedule',
    path: '/admin/create/create/schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCreateCreateEventRoute = AdminCreateCreateEventRouteImport.update({
  id: '/admin/create/create/event',
  path: '/admin/create/create/event',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateCreateClientMembershipRoute =
  AdminCreateCreateClientMembershipRouteImport.update({
    id: '/admin/create/create/client-membership',
    path: '/admin/create/create/client-membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCreateCreateBookingRoute =
  AdminCreateCreateBookingRouteImport.update({
    id: '/admin/create/create/booking',
    path: '/admin/create/create/booking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/view-members': typeof AdminViewMembersRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/schedule': typeof ClientScheduleRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/website/book': typeof WebsiteBookRoute
  '/website/consultations': typeof WebsiteConsultationsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/join': typeof WebsiteJoinRoute
  '/website/locations': typeof WebsiteLocationsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/products': typeof WebsiteProductsRoute
  '/website/services': typeof WebsiteServicesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/owner/owner/overview': typeof OwnerOwnerOverviewRoute
  '/owner/owner/retention': typeof OwnerOwnerRetentionRoute
  '/owner/owner/revenue': typeof OwnerOwnerRevenueRoute
  '/owner/owner/settings': typeof OwnerOwnerSettingsRoute
  '/website/services/$serviceId': typeof WebsiteServicesServiceIdRoute
  '/admin/create/create/booking': typeof AdminCreateCreateBookingRoute
  '/admin/create/create/client-membership': typeof AdminCreateCreateClientMembershipRoute
  '/admin/create/create/event': typeof AdminCreateCreateEventRoute
  '/admin/create/create/schedule': typeof AdminCreateCreateScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/view-members': typeof AdminViewMembersRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/schedule': typeof ClientScheduleRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/website/book': typeof WebsiteBookRoute
  '/website/consultations': typeof WebsiteConsultationsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/join': typeof WebsiteJoinRoute
  '/website/locations': typeof WebsiteLocationsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/products': typeof WebsiteProductsRoute
  '/website/services': typeof WebsiteServicesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/owner/owner/overview': typeof OwnerOwnerOverviewRoute
  '/owner/owner/retention': typeof OwnerOwnerRetentionRoute
  '/owner/owner/revenue': typeof OwnerOwnerRevenueRoute
  '/owner/owner/settings': typeof OwnerOwnerSettingsRoute
  '/website/services/$serviceId': typeof WebsiteServicesServiceIdRoute
  '/admin/create/create/booking': typeof AdminCreateCreateBookingRoute
  '/admin/create/create/client-membership': typeof AdminCreateCreateClientMembershipRoute
  '/admin/create/create/event': typeof AdminCreateCreateEventRoute
  '/admin/create/create/schedule': typeof AdminCreateCreateScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/view-members': typeof AdminViewMembersRoute
  '/client/billing': typeof ClientBillingRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/schedule': typeof ClientScheduleRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/website/book': typeof WebsiteBookRoute
  '/website/consultations': typeof WebsiteConsultationsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/join': typeof WebsiteJoinRoute
  '/website/locations': typeof WebsiteLocationsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/products': typeof WebsiteProductsRoute
  '/website/services': typeof WebsiteServicesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/owner/owner/overview': typeof OwnerOwnerOverviewRoute
  '/owner/owner/retention': typeof OwnerOwnerRetentionRoute
  '/owner/owner/revenue': typeof OwnerOwnerRevenueRoute
  '/owner/owner/settings': typeof OwnerOwnerSettingsRoute
  '/website/services/$serviceId': typeof WebsiteServicesServiceIdRoute
  '/admin/create/create/booking': typeof AdminCreateCreateBookingRoute
  '/admin/create/create/client-membership': typeof AdminCreateCreateClientMembershipRoute
  '/admin/create/create/event': typeof AdminCreateCreateEventRoute
  '/admin/create/create/schedule': typeof AdminCreateCreateScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start-demo'
    | '/style-guide'
    | '/admin/announcements'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/view-members'
    | '/client/billing'
    | '/client/dashboard'
    | '/client/schedule'
    | '/demo/clerk'
    | '/website/book'
    | '/website/consultations'
    | '/website/events'
    | '/website/join'
    | '/website/locations'
    | '/website/memberships'
    | '/website/products'
    | '/website/services'
    | '/admin/'
    | '/client/'
    | '/owner/owner/overview'
    | '/owner/owner/retention'
    | '/owner/owner/revenue'
    | '/owner/owner/settings'
    | '/website/services/$serviceId'
    | '/admin/create/create/booking'
    | '/admin/create/create/client-membership'
    | '/admin/create/create/event'
    | '/admin/create/create/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start-demo'
    | '/style-guide'
    | '/admin/announcements'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/view-members'
    | '/client/billing'
    | '/client/dashboard'
    | '/client/schedule'
    | '/demo/clerk'
    | '/website/book'
    | '/website/consultations'
    | '/website/events'
    | '/website/join'
    | '/website/locations'
    | '/website/memberships'
    | '/website/products'
    | '/website/services'
    | '/admin'
    | '/client'
    | '/owner/owner/overview'
    | '/owner/owner/retention'
    | '/owner/owner/revenue'
    | '/owner/owner/settings'
    | '/website/services/$serviceId'
    | '/admin/create/create/booking'
    | '/admin/create/create/client-membership'
    | '/admin/create/create/event'
    | '/admin/create/create/schedule'
  id:
    | '__root__'
    | '/'
    | '/start-demo'
    | '/style-guide'
    | '/admin/announcements'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/view-members'
    | '/client/billing'
    | '/client/dashboard'
    | '/client/schedule'
    | '/demo/clerk'
    | '/website/book'
    | '/website/consultations'
    | '/website/events'
    | '/website/join'
    | '/website/locations'
    | '/website/memberships'
    | '/website/products'
    | '/website/services'
    | '/admin/'
    | '/client/'
    | '/owner/owner/overview'
    | '/owner/owner/retention'
    | '/owner/owner/revenue'
    | '/owner/owner/settings'
    | '/website/services/$serviceId'
    | '/admin/create/create/booking'
    | '/admin/create/create/client-membership'
    | '/admin/create/create/event'
    | '/admin/create/create/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartDemoRoute: typeof StartDemoRoute
  StyleGuideRoute: typeof StyleGuideRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminViewMembersRoute: typeof AdminViewMembersRoute
  ClientBillingRoute: typeof ClientBillingRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientScheduleRoute: typeof ClientScheduleRoute
  DemoClerkRoute: typeof DemoClerkRoute
  WebsiteBookRoute: typeof WebsiteBookRoute
  WebsiteConsultationsRoute: typeof WebsiteConsultationsRoute
  WebsiteEventsRoute: typeof WebsiteEventsRoute
  WebsiteJoinRoute: typeof WebsiteJoinRoute
  WebsiteLocationsRoute: typeof WebsiteLocationsRoute
  WebsiteMembershipsRoute: typeof WebsiteMembershipsRoute
  WebsiteProductsRoute: typeof WebsiteProductsRoute
  WebsiteServicesRoute: typeof WebsiteServicesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  OwnerOwnerOverviewRoute: typeof OwnerOwnerOverviewRoute
  OwnerOwnerRetentionRoute: typeof OwnerOwnerRetentionRoute
  OwnerOwnerRevenueRoute: typeof OwnerOwnerRevenueRoute
  OwnerOwnerSettingsRoute: typeof OwnerOwnerSettingsRoute
  AdminCreateCreateBookingRoute: typeof AdminCreateCreateBookingRoute
  AdminCreateCreateClientMembershipRoute: typeof AdminCreateCreateClientMembershipRoute
  AdminCreateCreateEventRoute: typeof AdminCreateCreateEventRoute
  AdminCreateCreateScheduleRoute: typeof AdminCreateCreateScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-demo': {
      id: '/start-demo'
      path: '/start-demo'
      fullPath: '/start-demo'
      preLoaderRoute: typeof StartDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/services': {
      id: '/website/services'
      path: '/website/services'
      fullPath: '/website/services'
      preLoaderRoute: typeof WebsiteServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/products': {
      id: '/website/products'
      path: '/website/products'
      fullPath: '/website/products'
      preLoaderRoute: typeof WebsiteProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/memberships': {
      id: '/website/memberships'
      path: '/website/memberships'
      fullPath: '/website/memberships'
      preLoaderRoute: typeof WebsiteMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/locations': {
      id: '/website/locations'
      path: '/website/locations'
      fullPath: '/website/locations'
      preLoaderRoute: typeof WebsiteLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/join': {
      id: '/website/join'
      path: '/website/join'
      fullPath: '/website/join'
      preLoaderRoute: typeof WebsiteJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/events': {
      id: '/website/events'
      path: '/website/events'
      fullPath: '/website/events'
      preLoaderRoute: typeof WebsiteEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/consultations': {
      id: '/website/consultations'
      path: '/website/consultations'
      fullPath: '/website/consultations'
      preLoaderRoute: typeof WebsiteConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/book': {
      id: '/website/book'
      path: '/website/book'
      fullPath: '/website/book'
      preLoaderRoute: typeof WebsiteBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/schedule': {
      id: '/client/schedule'
      path: '/client/schedule'
      fullPath: '/client/schedule'
      preLoaderRoute: typeof ClientScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/billing': {
      id: '/client/billing'
      path: '/client/billing'
      fullPath: '/client/billing'
      preLoaderRoute: typeof ClientBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view-members': {
      id: '/admin/view-members'
      path: '/admin/view-members'
      fullPath: '/admin/view-members'
      preLoaderRoute: typeof AdminViewMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/admin/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/services/$serviceId': {
      id: '/website/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/website/services/$serviceId'
      preLoaderRoute: typeof WebsiteServicesServiceIdRouteImport
      parentRoute: typeof WebsiteServicesRoute
    }
    '/owner/owner/settings': {
      id: '/owner/owner/settings'
      path: '/owner/owner/settings'
      fullPath: '/owner/owner/settings'
      preLoaderRoute: typeof OwnerOwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/owner/revenue': {
      id: '/owner/owner/revenue'
      path: '/owner/owner/revenue'
      fullPath: '/owner/owner/revenue'
      preLoaderRoute: typeof OwnerOwnerRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/owner/retention': {
      id: '/owner/owner/retention'
      path: '/owner/owner/retention'
      fullPath: '/owner/owner/retention'
      preLoaderRoute: typeof OwnerOwnerRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/owner/overview': {
      id: '/owner/owner/overview'
      path: '/owner/owner/overview'
      fullPath: '/owner/owner/overview'
      preLoaderRoute: typeof OwnerOwnerOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create/create/schedule': {
      id: '/admin/create/create/schedule'
      path: '/admin/create/create/schedule'
      fullPath: '/admin/create/create/schedule'
      preLoaderRoute: typeof AdminCreateCreateScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create/create/event': {
      id: '/admin/create/create/event'
      path: '/admin/create/create/event'
      fullPath: '/admin/create/create/event'
      preLoaderRoute: typeof AdminCreateCreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create/create/client-membership': {
      id: '/admin/create/create/client-membership'
      path: '/admin/create/create/client-membership'
      fullPath: '/admin/create/create/client-membership'
      preLoaderRoute: typeof AdminCreateCreateClientMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create/create/booking': {
      id: '/admin/create/create/booking'
      path: '/admin/create/create/booking'
      fullPath: '/admin/create/create/booking'
      preLoaderRoute: typeof AdminCreateCreateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WebsiteServicesRouteChildren {
  WebsiteServicesServiceIdRoute: typeof WebsiteServicesServiceIdRoute
}

const WebsiteServicesRouteChildren: WebsiteServicesRouteChildren = {
  WebsiteServicesServiceIdRoute: WebsiteServicesServiceIdRoute,
}

const WebsiteServicesRouteWithChildren = WebsiteServicesRoute._addFileChildren(
  WebsiteServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartDemoRoute: StartDemoRoute,
  StyleGuideRoute: StyleGuideRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCheckInRoute: AdminCheckInRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminViewMembersRoute: AdminViewMembersRoute,
  ClientBillingRoute: ClientBillingRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientScheduleRoute: ClientScheduleRoute,
  DemoClerkRoute: DemoClerkRoute,
  WebsiteBookRoute: WebsiteBookRoute,
  WebsiteConsultationsRoute: WebsiteConsultationsRoute,
  WebsiteEventsRoute: WebsiteEventsRoute,
  WebsiteJoinRoute: WebsiteJoinRoute,
  WebsiteLocationsRoute: WebsiteLocationsRoute,
  WebsiteMembershipsRoute: WebsiteMembershipsRoute,
  WebsiteProductsRoute: WebsiteProductsRoute,
  WebsiteServicesRoute: WebsiteServicesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  OwnerOwnerOverviewRoute: OwnerOwnerOverviewRoute,
  OwnerOwnerRetentionRoute: OwnerOwnerRetentionRoute,
  OwnerOwnerRevenueRoute: OwnerOwnerRevenueRoute,
  OwnerOwnerSettingsRoute: OwnerOwnerSettingsRoute,
  AdminCreateCreateBookingRoute: AdminCreateCreateBookingRoute,
  AdminCreateCreateClientMembershipRoute:
    AdminCreateCreateClientMembershipRoute,
  AdminCreateCreateEventRoute: AdminCreateCreateEventRoute,
  AdminCreateCreateScheduleRoute: AdminCreateCreateScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
