/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as StartDemoRouteImport } from './routes/start-demo'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteScheduleRouteImport } from './routes/website.schedule'
import { Route as WebsiteMembershipsRouteImport } from './routes/website.memberships'
import { Route as WebsiteEventsRouteImport } from './routes/website.events'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffMembersRouteImport } from './routes/staff.members'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffCheckInRouteImport } from './routes/staff.check-in'
import { Route as StaffAnnouncementsRouteImport } from './routes/staff.announcements'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerRevenueRouteImport } from './routes/owner.revenue'
import { Route as OwnerRetentionRouteImport } from './routes/owner.retention'
import { Route as OwnerOverviewRouteImport } from './routes/owner.overview'
import { Route as MemberDashboardRouteImport } from './routes/member.dashboard'
import { Route as MemberClassesRouteImport } from './routes/member.classes'
import { Route as MemberBillingRouteImport } from './routes/member.billing'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as StaffCreateScheduleRouteImport } from './routes/staff.create.schedule'
import { Route as StaffCreateMembershipRouteImport } from './routes/staff.create.membership'
import { Route as StaffCreateEventRouteImport } from './routes/staff.create.event'
import { Route as StaffCreateClassesRouteImport } from './routes/staff.create.classes'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDemoRoute = StartDemoRouteImport.update({
  id: '/start-demo',
  path: '/start-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteScheduleRoute = WebsiteScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteMembershipsRoute = WebsiteMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteEventsRoute = WebsiteEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WebsiteRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMembersRoute = StaffMembersRouteImport.update({
  id: '/staff/members',
  path: '/staff/members',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCheckInRoute = StaffCheckInRouteImport.update({
  id: '/staff/check-in',
  path: '/staff/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAnnouncementsRoute = StaffAnnouncementsRouteImport.update({
  id: '/staff/announcements',
  path: '/staff/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRevenueRoute = OwnerRevenueRouteImport.update({
  id: '/owner/revenue',
  path: '/owner/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRetentionRoute = OwnerRetentionRouteImport.update({
  id: '/owner/retention',
  path: '/owner/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOverviewRoute = OwnerOverviewRouteImport.update({
  id: '/owner/overview',
  path: '/owner/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/member/dashboard',
  path: '/member/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberClassesRoute = MemberClassesRouteImport.update({
  id: '/member/classes',
  path: '/member/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBillingRoute = MemberBillingRouteImport.update({
  id: '/member/billing',
  path: '/member/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCreateScheduleRoute = StaffCreateScheduleRouteImport.update({
  id: '/staff/create/schedule',
  path: '/staff/create/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCreateMembershipRoute = StaffCreateMembershipRouteImport.update({
  id: '/staff/create/membership',
  path: '/staff/create/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCreateEventRoute = StaffCreateEventRouteImport.update({
  id: '/staff/create/event',
  path: '/staff/create/event',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCreateClassesRoute = StaffCreateClassesRouteImport.update({
  id: '/staff/create/classes',
  path: '/staff/create/classes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/website': typeof WebsiteRouteWithChildren
  '/demo/clerk': typeof DemoClerkRoute
  '/member/billing': typeof MemberBillingRoute
  '/member/classes': typeof MemberClassesRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/owner/overview': typeof OwnerOverviewRoute
  '/owner/retention': typeof OwnerRetentionRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/members': typeof StaffMembersRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/schedule': typeof WebsiteScheduleRoute
  '/staff/create/classes': typeof StaffCreateClassesRoute
  '/staff/create/event': typeof StaffCreateEventRoute
  '/staff/create/membership': typeof StaffCreateMembershipRoute
  '/staff/create/schedule': typeof StaffCreateScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/website': typeof WebsiteRouteWithChildren
  '/demo/clerk': typeof DemoClerkRoute
  '/member/billing': typeof MemberBillingRoute
  '/member/classes': typeof MemberClassesRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/owner/overview': typeof OwnerOverviewRoute
  '/owner/retention': typeof OwnerRetentionRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/members': typeof StaffMembersRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/schedule': typeof WebsiteScheduleRoute
  '/staff/create/classes': typeof StaffCreateClassesRoute
  '/staff/create/event': typeof StaffCreateEventRoute
  '/staff/create/membership': typeof StaffCreateMembershipRoute
  '/staff/create/schedule': typeof StaffCreateScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/start-demo': typeof StartDemoRoute
  '/style-guide': typeof StyleGuideRoute
  '/website': typeof WebsiteRouteWithChildren
  '/demo/clerk': typeof DemoClerkRoute
  '/member/billing': typeof MemberBillingRoute
  '/member/classes': typeof MemberClassesRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/owner/overview': typeof OwnerOverviewRoute
  '/owner/retention': typeof OwnerRetentionRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/members': typeof StaffMembersRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/website/events': typeof WebsiteEventsRoute
  '/website/memberships': typeof WebsiteMembershipsRoute
  '/website/schedule': typeof WebsiteScheduleRoute
  '/staff/create/classes': typeof StaffCreateClassesRoute
  '/staff/create/event': typeof StaffCreateEventRoute
  '/staff/create/membership': typeof StaffCreateMembershipRoute
  '/staff/create/schedule': typeof StaffCreateScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/start-demo'
    | '/style-guide'
    | '/website'
    | '/demo/clerk'
    | '/member/billing'
    | '/member/classes'
    | '/member/dashboard'
    | '/owner/overview'
    | '/owner/retention'
    | '/owner/revenue'
    | '/owner/settings'
    | '/staff/announcements'
    | '/staff/check-in'
    | '/staff/dashboard'
    | '/staff/members'
    | '/staff/settings'
    | '/website/events'
    | '/website/memberships'
    | '/website/schedule'
    | '/staff/create/classes'
    | '/staff/create/event'
    | '/staff/create/membership'
    | '/staff/create/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/start-demo'
    | '/style-guide'
    | '/website'
    | '/demo/clerk'
    | '/member/billing'
    | '/member/classes'
    | '/member/dashboard'
    | '/owner/overview'
    | '/owner/retention'
    | '/owner/revenue'
    | '/owner/settings'
    | '/staff/announcements'
    | '/staff/check-in'
    | '/staff/dashboard'
    | '/staff/members'
    | '/staff/settings'
    | '/website/events'
    | '/website/memberships'
    | '/website/schedule'
    | '/staff/create/classes'
    | '/staff/create/event'
    | '/staff/create/membership'
    | '/staff/create/schedule'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/start-demo'
    | '/style-guide'
    | '/website'
    | '/demo/clerk'
    | '/member/billing'
    | '/member/classes'
    | '/member/dashboard'
    | '/owner/overview'
    | '/owner/retention'
    | '/owner/revenue'
    | '/owner/settings'
    | '/staff/announcements'
    | '/staff/check-in'
    | '/staff/dashboard'
    | '/staff/members'
    | '/staff/settings'
    | '/website/events'
    | '/website/memberships'
    | '/website/schedule'
    | '/staff/create/classes'
    | '/staff/create/event'
    | '/staff/create/membership'
    | '/staff/create/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  StartDemoRoute: typeof StartDemoRoute
  StyleGuideRoute: typeof StyleGuideRoute
  WebsiteRoute: typeof WebsiteRouteWithChildren
  DemoClerkRoute: typeof DemoClerkRoute
  MemberBillingRoute: typeof MemberBillingRoute
  MemberClassesRoute: typeof MemberClassesRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  OwnerOverviewRoute: typeof OwnerOverviewRoute
  OwnerRetentionRoute: typeof OwnerRetentionRoute
  OwnerRevenueRoute: typeof OwnerRevenueRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  StaffAnnouncementsRoute: typeof StaffAnnouncementsRoute
  StaffCheckInRoute: typeof StaffCheckInRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffMembersRoute: typeof StaffMembersRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffCreateClassesRoute: typeof StaffCreateClassesRoute
  StaffCreateEventRoute: typeof StaffCreateEventRoute
  StaffCreateMembershipRoute: typeof StaffCreateMembershipRoute
  StaffCreateScheduleRoute: typeof StaffCreateScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-demo': {
      id: '/start-demo'
      path: '/start-demo'
      fullPath: '/start-demo'
      preLoaderRoute: typeof StartDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/schedule': {
      id: '/website/schedule'
      path: '/schedule'
      fullPath: '/website/schedule'
      preLoaderRoute: typeof WebsiteScheduleRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/memberships': {
      id: '/website/memberships'
      path: '/memberships'
      fullPath: '/website/memberships'
      preLoaderRoute: typeof WebsiteMembershipsRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/events': {
      id: '/website/events'
      path: '/events'
      fullPath: '/website/events'
      preLoaderRoute: typeof WebsiteEventsRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/members': {
      id: '/staff/members'
      path: '/staff/members'
      fullPath: '/staff/members'
      preLoaderRoute: typeof StaffMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/check-in': {
      id: '/staff/check-in'
      path: '/staff/check-in'
      fullPath: '/staff/check-in'
      preLoaderRoute: typeof StaffCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/announcements': {
      id: '/staff/announcements'
      path: '/staff/announcements'
      fullPath: '/staff/announcements'
      preLoaderRoute: typeof StaffAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/revenue': {
      id: '/owner/revenue'
      path: '/owner/revenue'
      fullPath: '/owner/revenue'
      preLoaderRoute: typeof OwnerRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/retention': {
      id: '/owner/retention'
      path: '/owner/retention'
      fullPath: '/owner/retention'
      preLoaderRoute: typeof OwnerRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/overview': {
      id: '/owner/overview'
      path: '/owner/overview'
      fullPath: '/owner/overview'
      preLoaderRoute: typeof OwnerOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/member/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/classes': {
      id: '/member/classes'
      path: '/member/classes'
      fullPath: '/member/classes'
      preLoaderRoute: typeof MemberClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/billing': {
      id: '/member/billing'
      path: '/member/billing'
      fullPath: '/member/billing'
      preLoaderRoute: typeof MemberBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/create/schedule': {
      id: '/staff/create/schedule'
      path: '/staff/create/schedule'
      fullPath: '/staff/create/schedule'
      preLoaderRoute: typeof StaffCreateScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/create/membership': {
      id: '/staff/create/membership'
      path: '/staff/create/membership'
      fullPath: '/staff/create/membership'
      preLoaderRoute: typeof StaffCreateMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/create/event': {
      id: '/staff/create/event'
      path: '/staff/create/event'
      fullPath: '/staff/create/event'
      preLoaderRoute: typeof StaffCreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/create/classes': {
      id: '/staff/create/classes'
      path: '/staff/create/classes'
      fullPath: '/staff/create/classes'
      preLoaderRoute: typeof StaffCreateClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WebsiteRouteChildren {
  WebsiteEventsRoute: typeof WebsiteEventsRoute
  WebsiteMembershipsRoute: typeof WebsiteMembershipsRoute
  WebsiteScheduleRoute: typeof WebsiteScheduleRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteEventsRoute: WebsiteEventsRoute,
  WebsiteMembershipsRoute: WebsiteMembershipsRoute,
  WebsiteScheduleRoute: WebsiteScheduleRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  StartDemoRoute: StartDemoRoute,
  StyleGuideRoute: StyleGuideRoute,
  WebsiteRoute: WebsiteRouteWithChildren,
  DemoClerkRoute: DemoClerkRoute,
  MemberBillingRoute: MemberBillingRoute,
  MemberClassesRoute: MemberClassesRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  OwnerOverviewRoute: OwnerOverviewRoute,
  OwnerRetentionRoute: OwnerRetentionRoute,
  OwnerRevenueRoute: OwnerRevenueRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  StaffAnnouncementsRoute: StaffAnnouncementsRoute,
  StaffCheckInRoute: StaffCheckInRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffMembersRoute: StaffMembersRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffCreateClassesRoute: StaffCreateClassesRoute,
  StaffCreateEventRoute: StaffCreateEventRoute,
  StaffCreateMembershipRoute: StaffCreateMembershipRoute,
  StaffCreateScheduleRoute: StaffCreateScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
